SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) RN
    FROM REST_INFO
) A
WHERE A.RN = 1
ORDER BY FOOD_TYPE DESC;