SELECT ID,
    CASE
        WHEN COLONY_GROUP = 1 THEN 'CRITICAL'
        WHEN COLONY_GROUP = 2 THEN 'HIGH'
        WHEN COLONY_GROUP = 3 THEN 'MEDIUM'
        WHEN COLONY_GROUP = 4 THEN 'LOW' END AS COLONY_NAME
FROM (SELECT *, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_GROUP FROM ECOLI_DATA ) AS A
ORDER BY ID