SELECT SUB.YEAR, SUB.MONTH, SUB.GENDER, COUNT(DISTINCT USER_ID) USERS
FROM (
    SELECT O.USER_ID, O.SALES_AMOUNT, U.GENDER, YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH
    FROM ONLINE_SALE O
    JOIN USER_INFO U
    ON O.USER_ID = U.USER_ID
    WHERE GENDER IS NOT NULL
) SUB
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;

    # SELECT O.USER_ID, O.SALES_AMOUNT, U.GENDER, YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH
    # FROM ONLINE_SALE O
    # LEFT JOIN USER_INFO U
    # ON O.USER_ID = U.USER_ID
    # WHERE GENDER IS NOT NULL