-- 코드를 입력하세요
SELECT
    YEAR(SALES_DATE) YEAR,
    MONTH(SALES_DATE) MONTH,
    COUNT(DISTINCT(A.USER_ID)),
    ROUND(
        COUNT(DISTINCT(A.USER_ID)) /
        (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021)
    , 1)
FROM USER_INFO A
RIGHT JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH