SELECT B.CAR_ID, IF(AVAILABILITY IS NULL, '대여 가능', '대여중') AS AVAILABILITY
FROM (
        SELECT CAR_ID, CASE WHEN START_DATE <= DATE_FORMAT('2022-10-16', '%Y-%m-%d') AND DATE_FORMAT('2022-10-16', '%Y-%m-%d') <= END_DATE THEN '대여중' ELSE NULL END AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    HAVING AVAILABILITY = '대여중'
) A RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
GROUP BY B.CAR_ID
ORDER BY CAR_ID DESC;