-- 코드를 입력하세요
# SELECT A.PRODUCT_ID, A.PRODUCT_NAME, 
# FROM FOOD_PRODUCT A

SELECT A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE * SUM(AMOUNT) TOTAL_SALES
# A.PRODUCT_ID PRODUCT_ID, A.PRODUCT_NAME PRODUCT_NAME, A.PRICE * B.AMOUNT TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN (
    SELECT *
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
) B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;