SELECT D.MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(E.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW E
RIGHT JOIN
(
    SELECT A.MEMBER_ID, C.MEMBER_NAME
    FROM REST_REVIEW A
    RIGHT JOIN MEMBER_PROFILE C
    ON A.MEMBER_ID = C.MEMBER_ID
    GROUP BY A.MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(B.REVIEW_COUNT) MAX_COUNT
        FROM (
            SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY REVIEW_COUNT DESC
        ) B
    )
) D
ON E.MEMBER_ID = D.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT