-- 코드를 작성해주세요

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS A
LEFT JOIN (
    SELECT SUM(CODE) CODE_SUM
    FROM SKILLCODES A
    WHERE A.NAME = "C#" OR A.NAME = "Python"
) B
ON A.SKILL_CODE & B.CODE_SUM > 0
WHERE A.SKILL_CODE & B.CODE_SUM > 0
ORDER BY A.ID

# SELECT SUM(CODE) CODE_SUM
# FROM SKILLCODES A
# WHERE A.NAME = "C#" OR A.NAME = "Python"