-- 코드를 작성해주세요

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS A
WHERE A.SKILL_CODE & (SELECT SUM(CODE) CODE_SUM
FROM SKILLCODES A
WHERE A.NAME = "C#" OR A.NAME = "Python") > 0
ORDER BY A.ID;



