SELECT FP.CATEGORY, FP.PRICE MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
JOIN (SELECT CATEGORY, MAX(PRICE) MAX
FROM FOOD_PRODUCT F
WHERE CATEGORY = '과자' || CATEGORY = '국' || CATEGORY = '김치' || CATEGORY = '식용유'
GROUP BY CATEGORY) SUB
ON FP.PRICE = SUB.MAX AND FP.CATEGORY = SUB.CATEGORY
ORDER BY MAX_PRICE DESC

# SELECT CATEGORY, MAX(PRICE) MAX
# FROM FOOD_PRODUCT F
# WHERE CATEGORY = '과자' || CATEGORY = '국' || CATEGORY = '김치' || CATEGORY = '식용유'
# GROUP BY CATEGORY

# SELECT *
# FROM FOOD_PRODUCT F
# WHERE CATEGORY = '과자' || CATEGORY = '국' || CATEGORY = '김치' || CATEGORY = '식용유'